apiVersion: v1 # this is just v1 because that's what the k8s docs says to use for services
kind: Service
metadata:
  name: backend
spec:
  selector: # identifies which other resources should be connected to this resource
  # define which pods should be part of this service
  # a service object exposes pods to the outside world
  # you don't control deployments with a service, but you do control pods
  # so we want to select the pods here we want the service to be associated with
    # you can only select on labels for services, so matchLabels is not needed to be explicitly set
    app: second-app
  ports: # is a list, so you could map multiple ports
    - protocol: 'TCP'
      port: 80 # port the outside world is exposed to
      targetPort: 8080 # port in the container
  type: LoadBalancer